language: r
# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

sudo: false
cache: packages

matrix:
  include:
   - r: release
   - r: devel
   - r: oldrel

after_success:
  - Rscript -e 'covr::codecov()'
